//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResEx.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap copyBase {
            get {
                object obj = ResourceManager.GetObject("copyBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture already exists!.
        /// </summary>
        public static string CultureAlreadyExistsError {
            get {
                return ResourceManager.GetString("CultureAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} resource file.
        ///Are you sure?.
        /// </summary>
        public static string DeletingResourceSetWarning {
            get {
                return ResourceManager.GetString("DeletingResourceSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string EditGridCommentColumnHeader {
            get {
                return ResourceManager.GetString("EditGridCommentColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string EditGridValueColumnHeader {
            get {
                return ResourceManager.GetString("EditGridValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found. Remove it from Recent File list?.
        /// </summary>
        public static string FileRemoveFromRecent {
            get {
                return ResourceManager.GetString("FileRemoveFromRecent", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap helpContents {
            get {
                object obj = ResourceManager.GetObject("helpContents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap helpSearch {
            get {
                object obj = ResourceManager.GetObject("helpSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hideTranslated {
            get {
                object obj = ResourceManager.GetObject("hideTranslated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length: {0} characters.
        ///You typed {1}..
        /// </summary>
        public static string MaximumLengthError {
            get {
                return ResourceManager.GetString("MaximumLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string Menu_Culture {
            get {
                return ResourceManager.GetString("Menu_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Culture.
        /// </summary>
        public static string Menu_CurrentCulture {
            get {
                return ResourceManager.GetString("Menu_CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide Translated.
        /// </summary>
        public static string Menu_HideTranslated {
            get {
                return ResourceManager.GetString("Menu_HideTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Toolbar.
        /// </summary>
        public static string Menu_MainToolbar {
            get {
                return ResourceManager.GetString("Menu_MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing file.
        /// </summary>
        public static string Menu_OpenToolTip {
            get {
                return ResourceManager.GetString("Menu_OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Menu_SaveToolTip {
            get {
                return ResourceManager.GetString("Menu_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type some text to search in grid.
        /// </summary>
        public static string Menu_SearchToolTip {
            get {
                return ResourceManager.GetString("Menu_SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available! Click Ok to go to {0} homepage....
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder {0} expected!.
        /// </summary>
        public static string PlaceholderExpectedError {
            get {
                return ResourceManager.GetString("PlaceholderExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated {0} out of {1}.
        /// </summary>
        public static string ProgressBarText {
            get {
                return ResourceManager.GetString("ProgressBarText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap resString {
            get {
                object obj = ResourceManager.GetObject("resString", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resString_locked {
            get {
                object obj = ResourceManager.GetObject("resString_locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resString_review {
            get {
                object obj = ResourceManager.GetObject("resString_review", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resString_translated {
            get {
                object obj = ResourceManager.GetObject("resString_translated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resXAdd {
            get {
                object obj = ResourceManager.GetObject("resXAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap resXDel {
            get {
                object obj = ResourceManager.GetObject("resXDel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current resource file &apos;{0}&apos; changed.
        ///Save changes?.
        /// </summary>
        public static string SaveChangesWarning {
            get {
                return ResourceManager.GetString("SaveChangesWarning", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string(s).
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TreeNavigatorAllText {
            get {
                return ResourceManager.GetString("TreeNavigatorAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string TreeNavigatorRootText {
            get {
                return ResourceManager.GetString("TreeNavigatorRootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string WordCountLabel {
            get {
                return ResourceManager.GetString("WordCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        public static string YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveTheLatestVersion", resourceCulture);
            }
        }
    }
}
